In [2]:
import numpy
import matplotlib.pyplot as plt
import cv2
%matplotlib inline

# 读取图片
img = cv2.imread('dog.png')
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [16]:
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [5]:
def show_img(w_name, image):
    cv2.imshow(w_name, image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
show_img('small_dog', img)

In [4]:
# img的shape属性
img.shape

(339, 421, 3)

In [15]:
# 读取为灰度图
img_gray = cv2.imread('dog.png', cv2.IMREAD_GRAYSCALE)

In [9]:
# 展示灰度图
show_img('gray_dog', img_gray)

In [10]:
# 查看灰度图的shape
img_gray.shape

(339, 421)

In [15]:
# 把灰度图保存到指定路径
cv2.imwrite('gray_dog.png', img_gray)

True

In [16]:
img_gray.size

142719

In [37]:
# 视频打开
vc = cv2.VideoCapture('cxk.mp4')

In [38]:
while vc.isOpened():
    is_open, frame = vc.read()
    if is_open == False:
        break
    cv2.imshow('cxk', cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY))
    if (cv2.waitKey(10) & 0xFF) == 27:
        break
vc.release()
cv2.destroyAllWindows()

In [40]:
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [41]:
img.shape

(339, 421, 3)

In [46]:
show_img('region-test', img[100:300, 0:200])

In [3]:
b,g,r = cv2.split(img)

In [48]:
b

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [49]:
img_c = img.copy()
img_c[:,:,0] = 0
img_c[:,:,1] = 0
# 只保留r通道
show_img('r', img_c)

In [11]:
img_merge = cv2.merge((b,g,r))
# 只保留r通道
show_img('merge-test', img_merge)

In [23]:
show_img('make-border', cv2.copyMakeBorder(img_gray, 50,50,50,50,borderType=cv2.BORDER_WRAP))

In [33]:
img1 = img[50:65, 60:65]
img2 = img[50:65, 60:65]
cv2.add(img1, img2)

array([[[124, 255, 255],
        [128, 255, 255],
        [130, 255, 255],
        [132, 255, 255],
        [132, 255, 255]],

       [[124, 255, 255],
        [126, 255, 255],
        [128, 255, 255],
        [130, 255, 255],
        [130, 255, 255]],

       [[124, 255, 255],
        [124, 255, 255],
        [126, 255, 255],
        [128, 255, 255],
        [128, 255, 255]],

       [[122, 255, 255],
        [124, 255, 255],
        [126, 255, 255],
        [128, 255, 255],
        [126, 255, 255]],

       [[122, 255, 255],
        [124, 255, 255],
        [126, 255, 255],
        [128, 255, 255],
        [126, 255, 255]],

       [[122, 255, 255],
        [124, 255, 255],
        [126, 255, 255],
        [128, 255, 255],
        [124, 255, 255]],

       [[122, 255, 255],
        [124, 255, 255],
        [126, 255, 255],
        [128, 255, 255],
        [124, 255, 255]],

       [[122, 255, 255],
        [124, 255, 255],
        [126, 255, 255],
        [126, 255, 255],
        [12

In [34]:
img.shape

(339, 421, 3)

In [35]:
img2 = cv2.imread('cat.png')

In [36]:
img2.shape

(319, 359, 3)

In [51]:
img2 = cv2.resize(img2, (0, 0), fx=3, fy = 2)

In [52]:
img2.shape

(678, 1263, 3)

In [53]:
show_img('resize_cat', img2)

In [49]:
res = cv2.addWeighted(img, 0.5, img2, 0.5, 0)

In [50]:
show_img('res', res)